# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

before_script:
  - export LANG=en_US.UTF-8
  - cd Example ; pod install ; cd ..

script:
- xctool test -workspace Example/Yosaku.xcworkspace -scheme Yosaku -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
